version: '2'
services:
    mysql-php5.2:
        image: mysql:5.7
        volumes:
            - "/d/dev/public/database/data/server1:/var/lib/mysql"
        ports:
            - "6603:3306"    
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: simples
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
    web-apache2:
        image: httpd:2.2.32
    web-php5.2:
        volumes:
            - "/d/www/server_docker/server1:/var/www/html"
        depends_on:
            - mysql-php5.2
            - web-apache2
        image: sartorifelipe/php5.2
        links:
            - mysql-php5.2
            - web-apache2
        ports:
            - "8086:80"
        restart: always